Updated all CI

diff --git a/.github/workflows/pr-1-ci.yml b/.github/workflows/pr-1-ci.yml
--- a/.github/workflows/pr-1-ci.yml
+++ b/.github/workflows/pr-1-ci.yml
@@ -1,16 +1,18 @@
 name: PR Checks
 on:
-  pull_request:
-    branches:
-      - 'release-*'
-      - 'dev-*'
-    paths-ignore:
-      # These are ignored because they don't have anything to do with the model itself
-      - .github/**
-      - tools/**
-      - doc/**
-      - .*
-      - metadata.yaml
+  workflow_call:
+  # pull_request:
+  #   branches:
+  #     - 'release-*'
+  #     - 'dev-*'
+  #   paths-ignore:
+  #     # These are ignored because they don't have anything to do with the model itself
+  #     - .github/**
+  #     - tools/**
+  #     - doc/**
+  #     - .*
+  #     - metadata.yaml
+  #     - README.md
 jobs:
   commit-check:
     name: Commit Check
@@ -30,16 +32,66 @@ jobs:
         id: head-commit
         run: echo "authorship=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
 
+  branch-check:
+    name: PR Source Branch Check
+    # This check is run to confirm that the source branch is of the form `dev-<config>`
+    # and the target branch is of the form `release-<config>`. We are being especially
+    # concerned with branch names because deployment to GitHub Environments can only
+    # be done on source branches with a certain pattern. See #20.
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
+
+      - name: Check Source
+        run: |
+          if [[ "${{ startsWith(github.head_ref, 'dev-') }}" == "false" ]]; then
+            echo "::error::Source branch ${{ github.head_ref }} doesn't match 'dev-*'"
+            exit 1
+          fi
+
+      - name: Check Target
+        run: |
+          if [[ "${{ startsWith(github.base_ref, 'release-') }}" == "false" ]]; then
+            echo "::error::Target branch ${{ github.base_ref }} doesn't match 'release-*'"
+            exit 1
+          fi
+
+      - name: Compare Source and Target Config Names
+        # In this step, we cut the 'dev-' and 'release-' to compare config names directly.
+        run: |
+          source=$(cut --delimiter '-' --field 2- <<< "${{ github.head_ref }}")
+          target=$(cut --delimiter '-' --field 2- <<< "${{ github.base_ref }}")
+          if [[ "${source}" != "${target}" ]]; then
+            echo "::error::Config name of Source branch '${source}' does not match Target branch '${target}'"
+            exit 1
+          fi
+
+      - name: Failure Notifier
+        if: failure()
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_REPO: ${{ github.repository }}
+          BODY: |
+            :x: Automated testing cannot be run on this branch :x:
+            Source and Target branches must be of the form `dev-<config>` and `release-<config>` respectively, and `<config>` must match between them.
+            Rename the Source branch or check the Target branch, and try again.
+        run: gh pr comment --body '${{ env.BODY }}'
+
   repro-ci:
     # run the given config on the deployment GitHub Environment (`environment-name`) and
     # upload the checksums and test details
     needs:
       - commit-check
-    if: needs.commit-check.outputs.authorship != 'github-actions'
-    uses: codegat-test-org/actions/.github/workflows/checks.yml@main
+      - branch-check
+    if: needs.commit-check.outputs.authorship != 'github-actions' && needs.branch-check.result == 'success'
+    uses: access-nri/reproducibility/.github/workflows/checks.yml@main
     with:
       model-name: access-om2
-      environment-name: test
+      environment-name: Gadi
       config-tag: ${{ github.head_ref }}
       test-markers: checksum
     secrets: inherit
@@ -82,7 +134,7 @@ jobs:
         id: tests
         uses: EnricoMi/publish-unit-test-result-action/composite@e780361cd1fc1b1a170624547b3ffda64787d365  #v2.12.0
         with:
-          files: test_report.xml
+          files: ${{ env.TESTING_LOCAL_LOCATION }}/checksum/test_report.xml
           comment_mode: off
           check_run: true
           compare_to_earlier_commit: false
@@ -124,7 +176,7 @@ jobs:
             :white_check_mark: The Bitwise Reproducibility check succeeded when comparing against `${{ needs.check-checksum.outputs.compared-checksum-version }}` for this `Release` config. :white_check_mark:
             For further information, the experiment can be found on Gadi at ${{ needs.repro-ci.outputs.experiment-location }}, and the test results at ${{ needs.check-checksum.outputs.check-run-url }}.
             Consider bumping the minor version of `access-om2-configs` - to bump the version, comment `!bump minor`. The meaning of these version bumps is explained in the README.md, under `Config Tags`.
-        run: gh pr comment --body "${{ env.BODY }}"
+        run: gh pr comment --body '${{ env.BODY }}'
 
       - name: Successful Dev Comment
         if: needs.check-checksum.outputs.result == 'pass' && startsWith(github.base_ref, 'dev-')
@@ -132,7 +184,7 @@ jobs:
           BODY: |
             :white_check_mark: The Bitwise Reproducibility check succeeded when comparing against `${{ needs.check-checksum.outputs.compared-checksum-version }}` for this `Dev` config. :white_check_mark:
             For further information, the experiment can be found on Gadi at ${{ needs.repro-ci.outputs.experiment-location }}, and the test results at ${{ needs.check-checksum.outputs.check-run-url }}.
-        run: gh pr comment --body "${{ env.BODY }}"
+        run: gh pr comment --body '${{ env.BODY }}'
 
       - name: Failed Release Comment
         if: needs.check-checksum.outputs.result == 'fail' && startsWith(github.base_ref, 'release-')
@@ -141,7 +193,7 @@ jobs:
             :x: The Bitwise Reproducibility check failed when comparing against `${{ needs.check-checksum.outputs.compared-checksum-version }}` for this `Release` config. :x:
             For further information, the experiment can be found on Gadi at ${{ needs.repro-ci.outputs.experiment-location }}, and the test results at ${{ needs.check-checksum.outputs.check-run-url }}.
             You must bump the major version of `access-om2-configs` before this PR is merged to account for this - to bump the version, comment `!bump major`. The meaning of these version bumps is explained in the README.md, under `Config Tags`.
-        run: gh pr comment --body "${{ env.BODY }}"
+        run: gh pr comment --body '${{ env.BODY }}'
 
       - name: Failed Dev Comment
         if: needs.check-checksum.outputs.result == 'fail' && startsWith(github.base_ref, 'dev-')
@@ -149,4 +201,4 @@ jobs:
           BODY: |
             :warning: The Bitwise Reproducibility check failed when comparing against `${{ needs.check-checksum.outputs.compared-checksum-version }}` for this `Dev` config. :warning:
             For further information, the experiment can be found on Gadi at ${{ needs.repro-ci.outputs.experiment-location }}, and the test results at ${{ needs.check-checksum.outputs.check-run-url }}.
-        run: gh pr comment --body "${{ env.BODY }}"
+        run: gh pr comment --body '${{ env.BODY }}'
